# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WebService-Yandex-Suggest
version:      1.00
version_from: lib/WebService/Yandex/Suggest.pm
installdirs:  site
requires:
    LWP::UserAgent:                0
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
